// Code generated by sqlc. DO NOT EDIT.
// source: post_num.sql

package db

import (
	"context"
)

const createPost_Num = `-- name: CreatePost_Num :exec
INSERT INTO post_num (post_id)
VALUES (?)
`

func (q *Queries) CreatePost_Num(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, createPost_Num, postID)
	return err
}

const updatePost_Num_Star = `-- name: UpdatePost_Num_Star :exec
UPDATE post_num
SET star_num = (star_num + ?)
WHERE post_id = ?
`

type UpdatePost_Num_StarParams struct {
	StarNum int64 `json:"star_num"`
	PostID  int64 `json:"post_id"`
}

func (q *Queries) UpdatePost_Num_Star(ctx context.Context, arg UpdatePost_Num_StarParams) error {
	_, err := q.db.ExecContext(ctx, updatePost_Num_Star, arg.StarNum, arg.PostID)
	return err
}

const updatePost_Num_Visited = `-- name: UpdatePost_Num_Visited :exec
UPDATE post_num
SET visited_num = (visited_num + ?)
WHERE post_id = ?
`

type UpdatePost_Num_VisitedParams struct {
	VisitedNum int64 `json:"visited_num"`
	PostID     int64 `json:"post_id"`
}

func (q *Queries) UpdatePost_Num_Visited(ctx context.Context, arg UpdatePost_Num_VisitedParams) error {
	_, err := q.db.ExecContext(ctx, updatePost_Num_Visited, arg.VisitedNum, arg.PostID)
	return err
}
