// Code generated by sqlc. DO NOT EDIT.
// source: tops.sql

package db

import (
	"context"
)

const createTop = `-- name: CreateTop :exec
INSERT INTO tops (id, post_id)
VALUES (?, ?)
`

type CreateTopParams struct {
	ID     int64 `json:"id"`
	PostID int64 `json:"post_id"`
}

func (q *Queries) CreateTop(ctx context.Context, arg CreateTopParams) error {
	_, err := q.db.ExecContext(ctx, createTop, arg.ID, arg.PostID)
	return err
}

const deleteTopByPostID = `-- name: DeleteTopByPostID :exec
DELETE
FROM tops
WHERE post_id = ?
`

func (q *Queries) DeleteTopByPostID(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTopByPostID, postID)
	return err
}

const getTopByPostID = `-- name: GetTopByPostID :one
SELECT id, post_id
FROM tops
where post_id = ?
`

func (q *Queries) GetTopByPostID(ctx context.Context, postID int64) (Top, error) {
	row := q.db.QueryRowContext(ctx, getTopByPostID, postID)
	var i Top
	err := row.Scan(&i.ID, &i.PostID)
	return i, err
}
